### ISSUE TITLE
add 2048 game in website

### ISSUE THREAD

**Issue by HeyLoon** [tnfshcec/tnfshcec-web#27]
rt

**Comment by HeyLoon** [comment]
now project move to https://github.com/tnfshcec/cxk-2048-svelte

**Comment by HeyLoon** [comment]
@Eggrror404 can you help me solve the problems in 2048 branch @@? why not working💩

**Comment by Eggrror404** [comment]
> @Eggrror404 can you help me solve the problems in 2048 branch @@? why not working💩

寫了comment

**Comment by HeyLoon** [comment]
> > @Eggrror404 can you help me solve the problems in 2048 branch @@? why not working💩
> 
> 寫了comment

炸裂しました

**Comment by Eggrror404** [comment]
not in current interest :)
