### ISSUE TITLE
Play kmt national anthem to reclaim mainland china

### ISSUE THREAD

**Issue by HeyLoon** [tnfshcec/tnfshcec-web#30]
add a players

**Comment by HeyLoon** [comment]
https://github.com/fengkx/svelte-aplayer

**Comment by Eggrror404** [comment]
不知道你要怎麼用

但我覺得用這有點多餘
他有點肥

如果只是要簡單的播放器
自己寫不會很難

**Comment by HeyLoon** [comment]
@Eggrror404 主要是子母畫面和字幕不好寫，用現成的會比較快。
這部分如果之後發現功能過剩的話，再以最終成品為樣本復現之。

**Comment by Eggrror404** [comment]
確 先參考他的功能

> 主要是子母畫面和字幕不好寫

雖然我是不知道為什麼會需要這些功能
子母畫面？？

**Comment by HeyLoon** [comment]
> 雖然我是不知道為什麼會需要這些功能
> 子母畫面？？

類此功能平時不可行，卻不知是否為用，故嘗之。

**Comment by Eggrror404** [comment]
那你先開個個人項目測試
測試完再丟過來👍

**Comment by Eggrror404** [comment]
自己先測試
https://kit.svelte.dev/docs/creating-a-project

**Comment by HeyLoon** [comment]
沒看過那麼爛的專案，刪庫跑路

**Comment by HeyLoon** [comment]
幹你娘按錯

**Comment by Eggrror404** [comment]
@HeyLoon 不然做個點歌系統
大家點歌來播

**Comment by HeyLoon** [comment]
> @HeyLoon 不然做個點歌系統
> 大家點歌來播

汝言甚安吾意！

**Comment by Eggrror404** [comment]
> > @HeyLoon 不然做個點歌系統
> > 大家點歌來播
> 
> 汝言甚安吾意！

https://github.com/tnfshcec/tnfshcec-web/issues/31
