### ISSUE TITLE
Language specific paths doesn't seem to be prerendered

### ISSUE THREAD

**Issue by Eggrror404** [tnfshcec/tnfshcec-web#63]
when you go to https://www.tnfshcec.com/en
directly, it'd be a 404.

We're using inlang to generate the language paths, and are not manually creating the language paths ourselves. This probably caused the problem as SvelteKit doesn't know that they exist.

Im not sure what the fix will be yet; theres probably something to do with the inlang sveltekit integration.

**Comment by HeyLoon** [comment]
I don't think this is a bug that needs to be fixed. It's a legitimate feature🤔

**Comment by HeyLoon** [comment]
In my opinion,
What we should fix is not to make sure the /en or /jp path is working. We only need ONE result on Google. We can just use robots.txt or sth to tell Google not to crawl those URLs.

**Comment by Eggrror404** [comment]
k the bug is quite weird

when I do `npm run build` on local machine the paths do get generated;
I'm not sure why Github running it wouldn't.

> In my opinion,
> What we should fix is not to make sure the /en or /jp path is working. We only need ONE result on Google. We can just use robots.txt or sth to tell Google not to crawl those URLs.

Google only shows one result, for the language the user is in (or the language google thinks the user is in), and that would be one of our supported languages.
It's not that all three languages will show on search results, it's that we'd want to let Google show the language the user wants.
Also the three will (probably) never be shown together, because we do specify that they are the same page, in different languages :)

**Comment by Eggrror404** [comment]
broken since https://github.com/tnfshcec/tnfshcec-web/actions/runs/8167699243 (commit d8c03f2)

so this might be some dependency issue

**Comment by Eggrror404** [comment]
the routes are still not there
the tests didnt even catch it 🤧
