### ISSUE TITLE
The "Importance" block looks so fking weird when it under the code block.

### ISSUE THREAD

**Issue by HeyLoon** [tnfshcec/tnfshcec-web#70]
code:
![螢幕擷取畫面 2024-03-09 203642](https://github.com/tnfshcec/tnfshcec-web/assets/43095336/0a436605-fdc3-4ed1-850f-4b34d266179b)
what it actually looks on web:
![螢幕擷取畫面 2024-03-09 203740](https://github.com/tnfshcec/tnfshcec-web/assets/43095336/cb62d339-6e46-4a7a-9d9e-76a9592e78bd)
?
what happend? Transformer?

**Comment by Eggrror404** [comment]
actually every alert and codeblock side by side would look like that

its a problem with the custom components i built for them and i thought i fixed it in #67 ?

**Comment by Eggrror404** [comment]
btw i think you can create the outer codeblock with 4 backticks
