### ISSUE TITLE
Styling / Display Updates

### ISSUE THREAD

**Issue by Eggrror404** [tnfshcec/tnfshcec-web#76]
- better colors (#33)
- smaller max-width on posts (CenteredPage.svelte)
- `lang` field for markdown
- manage images in markdown
- remark-autolink-headings and remark-toc
- (maybe) improve codeblocks
- (maybe) cleanup global styles

**Comment by HeyLoon** [comment]
Buddy, this message can be deleted, I don't mind. It's not that easy to break through my defenses, really. I don't easily let my guard down, but one of my friends might be feeling a bit overwhelmed. He's not feeling well and wants to rest. Of course, it's not me. I've always been fine. Just look at it from the perspective of an observer. It's not like I'm letting my guard down. I just want to take care of my friend's feelings. He seems a bit vulnerable. I suggest deleting it. Of course, it's up to you whether to delete it or not. I don't feel anything, I just feel a bit unfair for my friend. It's not that easy to break through my defenses. Please, delete it.
